#!/usr/bin/env bash
# This script prints numbers from 1 to 100 but,
# displays Fizz on multiples of 3
# displays Buzz on multiples of 5
# displays FizzBuzz on multiples of 3 and 5

c=1
while ((c <= 100))
do
    if ((c % 15 == 0))
    then
       echo "FizzBuzz"
    elif ((c % 3 == 0))
    then
	echo "Fizz"
    elif ((c % 5 == 0))
    then
	echo "Buzz"
    else
	echo "$c"
    fi
((c++))
done
