#!/usr/bin/env bash
# This script prints Holberton School ten times, but
# on the 4th iteration prints bad luck
# on the 8th iteration prints good luck

c=0
while ((c < 10))
do
      if [ $c -eq 7 ]
      then
	  echo "good luck"
      elif [ $c -eq 3 ]
      then
	  echo "bad luck"
      else
	  echo "Holberton School"
      fi
      ((c++))
done
