#!/usr/bin/env bash
# This script gives information about the holbertonschool file:
# Checks if it exists
# Checks if it is empty
# Checks if it is a regular file

c="holbertonschool"

if [ -e $c ]
then
	echo "holbertonschool file exists"

	if [ -s $c ]
	then
		echo "holbertonschool file is not empty"
	else
		echo "holbertonschool file is empty"
	elif

	if [ -f $c ]
	then
		echo "holbertonschool is a regular file"
	fi

else
	echo "holbertonschool file does not exist"
fi